_core:
  default_config_hash: 4GIX5Esnc_umpXUBj4IIocRX7Mt5fPhm4AgXfE3E56E
module:
  announcements_feed: 0
  automated_cron: 0
  basic_auth: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  comment: 0
  config: 0
  consumers: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  decoupled_router: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  flexible_permissions: 0
  gin_toolbar: 0
  graphql: 0
  graphql_compose: 0
  group: 0
  help: 0
  history: 0
  image: 0
  jsonapi: 0
  link: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  migrate: 0
  migrate_plus: 0
  mysql: 0
  next: 0
  next_extras: 0
  next_graphql: 0
  next_jsonapi: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  pgov_migrate: 0
  search: 0
  serialization: 0
  shortcut: 0
  simple_oauth: 0
  subrequests: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  type_tray: 0
  typed_data: 0
  update: 0
  user: 0
  variationcache: 0
  views_ui: 0
  pathauto: 1
  views: 10
  minimal: 1000
theme:
  claro: 0
  gin: 0
  olivero: 0
profile: minimal
