_core:
  default_config_hash: Sd_9jXBxw3mGn9d_y94jvlitI0wpvj6x2dQ0p6aGhJo
entity_config:
  block_content:
    basic:
      enabled: true
      query_load_enabled: true
      edges_enabled: true
      routes_enabled: true
  image_style:
    1x1_third:
      enabled: false
    media_library:
      enabled: true
    thumbnail:
      enabled: true
  media:
    document:
      enabled: true
      query_load_enabled: true
      edges_enabled: true
      routes_enabled: true
    image:
      enabled: true
      query_load_enabled: true
      edges_enabled: true
      routes_enabled: true
    remote_video:
      enabled: true
      query_load_enabled: true
      edges_enabled: true
      routes_enabled: true
    video:
      enabled: true
      query_load_enabled: true
      edges_enabled: true
      routes_enabled: true
  menu:
    account:
      enabled: false
    admin:
      enabled: false
    footer:
      enabled: false
    main:
      enabled: false
    tools:
      enabled: false
  node:
    administration:
      enabled: false
    agency:
      enabled: true
      query_load_enabled: true
      edges_enabled: true
      routes_enabled: true
    article:
      enabled: false
    division:
      enabled: false
    period:
      enabled: false
    goal:
      enabled: true
      query_load_enabled: true
      edges_enabled: true
      routes_enabled: true
    milestone:
      enabled: false
    objective:
      enabled: false
    page:
      enabled: false
    plan:
      enabled: true
      query_load_enabled: true
      edges_enabled: true
      routes_enabled: true
    project:
      enabled: false
    subgoal:
      enabled: true
      query_load_enabled: true
      edges_enabled: true
      routes_enabled: true
    update:
      enabled: false
  taxonomy_term:
    designations:
      enabled: false
    tags:
      enabled: true
      query_load_enabled: true
      edges_enabled: true
      routes_enabled: true
    topics:
      enabled: true
      query_load_enabled: true
      edges_enabled: true
      routes_enabled: true
  user:
    user:
      enabled: false
field_config:
  media:
    document:
      field_media_document:
        enabled: true
    image:
      field_media_image:
        enabled: true
    remote_video:
      field_media_oembed_video:
        enabled: true
    video:
      field_media_video_file:
        enabled: true
  node:
    agency:
      body:
        enabled: true
      field_acronym:
        enabled: true
      field_link:
        enabled: true
      field_logo:
        enabled: true
    goal:
      body:
        enabled: true
      field_id:
        enabled: true
      field_parent:
        enabled: true
      field_plan:
        enabled: true
      field_topics:
        enabled: true
    plan:
      body:
        enabled: true
      field_agency:
        enabled: true
      field_date:
        enabled: true
      field_division:
        enabled: true
      field_link:
        enabled: true
    subgoal: {  }
  taxonomy_term:
    topics: {  }
settings:
  exclude_unpublished: true
  expose_entity_ids: false
  field_required_override: false
  schema_description: 'GraphQL Compose'
  schema_version: '1'
  simple_queries: true
  simple_unions: true
  site_name: false
  site_slogan: false
  site_front: true
  inflector_langcode: en
  inflector_singularize: true
