_core:
  default_config_hash: FLJZME3II5fjmMSrdEvJHp95ZJf8V_X0jbX0VdVU1BU
shield_enable: true
credential_provider: shield
credentials:
  shield:
    user: pgov
    pass: civicactions
allow_cli: true
debug_header: true
unset_basic_auth_headers: true
print: ''
method: 0
paths: ''
allowlist: ''
http_method_allowlist:
  get: get
  post: post
  delete: delete
  put: put
domains: performance.ddev.site
