<?php

use Drupal\field\Entity\FieldStorageConfig;
use Drupal\Core\Entity\ContentEntityInterface;

/**
 * Restrict the list of available "Time period" fields based on its content.
 *
 * Time periods are stored as entity references to Storage entities, such that
 * multiple items of the same time period can be grouped consistently. This
 * function reduces the list of all possible time periods to common sense
 * options based on the situation at hand.
 *
 * In general, this means following the hierarchy of content: Strategic plans
 * are parents of Goals; Goals are parents to Objectives; and so-on. It should
 * not be possible to set a Goal's value outside the date range of its parent
 * plan.
 *
 * Additionally, some of the date ranges are tracked as federal fiscal years
 * (Oct-Sept), while others follow calendar years (Jan-Dec). Ensure that the
 * selected duration type applies downstream.
 *
 * @param \Drupal\field\Entity\FieldStorageConfig $definition
 * @param \Drupal\Core\Entity\ContentEntityInterface|NULL $entity
 * @param $cacheable
 *
 * @return array
 *   A list of date range entities suitable for an entity reference field widget.
 */
function pgov_period_allowed_values(FieldStorageConfig $definition, ContentEntityInterface $entity = NULL, $cacheable) {
  $options = [];
  $query = \Drupal::entityQuery('storage')
    ->accessCheck(TRUE)
    ->condition('type', 'period');

  // Strategic Plan: more than 1 year, within the Administration's duration.

  // Goal: If a plan is referenced: within duration and duration type.

  // Measurement: Indicator->Objective->Goal, within duration and duration type.

  return $options;
}
